### ISSUE TITLE
Automatically save video to a specified folder, file and format

### ISSUE THREAD

**Issue by greenm1nd3d** [QuickBlox/javascript-media-recorder#11]
Is there a way to automatically save video to a specified folder, file and format without having to click the Download button, and without prompting the user / activating the browser's Save dialog?

**Comment by dimaspirit** [comment]
Hello, @greenm1nd3d . You could specify mime type and file name only, not a specified folder.
Check out doc https://quickblox.github.io/javascript-media-recorder/docs/QBMediaRecorder.html#.isAvailable

**Comment by Elagoon2017** [comment]
Hello, 

I have integrated the system.Audio and video cal in coming but
I have added qbMediaRecorderJS but no recording button or option come??

Please help to integrate this.

https://demo.switch2webpro.com/leitaaf/webcall/

**Comment by Elagoon2017** [comment]
Hello,

I have integrated the system.Audio and video cal in coming but
I have added qbMediaRecorderJS but no recording button or option come??

Please help to integrate this.

https://demo.switch2webpro.com/leitaaf/webcall/

**Comment by Elagoon2017** [comment]
Can i get any help regarding ,qbMediaRecorderJS i can not find any solution for that.I can not find any button for recording.
