### ISSUE TITLE
recording in mp4 format

### ISSUE THREAD

**Issue by utkarshmaximess** [QuickBlox/javascript-media-recorder#4]
hi, i am tryin to download file in mp4 format but i am not able to do so qbmediarecorder is downloading it in webm format only. I passed following parameter during recorder initialisation 

var recorderOpts = {
                callbacks: {
                    onStart: function onStartRecord() {
		                        console.log('[QB Recorder] onStartRecording');
		                      

                    },
                    onStop: function(blob) {
                        console.log('[QB Recorder] onStopRecording');
                        

                        var down = confirm('Do you want to download video?');

                        if(down) {
                            recorder.download('recording' + Date.now(), blob);
                        }

                        //recorder = null;
                    },
                    onError: function(error) {
                        console.error('Recorder error', error);
                    },

                },
                mimeType:'video/mp4'
            };
Then i ran the following code to check supporte media types and got the following result

var mimeType = qbMediaRecorder.getSupportedMimeTypes('video');
            console.info(`Call will recording in ${mimeType[0]}`);
            console.log(mimeType);
Console log:-
Call will recording in video/webm;codecs=h264
video.html:226 ["video/webm;codecs=h264", "video/webm;codecs=vp9", "video/webm;codecs=vp8", "video/webm"]

**Comment by dimaspirit** [comment]
@utkarshmaximess qbMediaRecorder.getSupportedMimeTypes('video') returns all types what are available. So,  your browser supported

>  video.html:226 ["video/webm;codecs=h264", "video/webm;codecs=vp9", "video/webm;codecs=vp8", "video/webm"]
only this.
Chrome doesn't use mp4 as a container. You need to choose one of them.

After saving a file you can convert by third-party tool, for example, https://cloudconvert.com/api

All types what Chrome supported in different versions  - https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

**Comment by dimaspirit** [comment]
@utkarshmaximess Is this resolving your question?
